# -*- coding: utf-8 -*-
from setuptools import setup, find_packages
from aldryn_newsblog import __version__

REQUIREMENTS = [
    'Django>=1.6,<1.10',
    'python-dateutil',
    'aldryn-apphooks-config==0.3.3',
    'aldryn-boilerplates==0.7.5',
    'aldryn-categories==1.1.0',
    'aldryn-common==1.0.4',
    'aldryn-people==1.2.2',
    'aldryn-reversion==1.1.0',
    'aldryn-translation-tools==0.2.1',
    'backport_collections==0.1',
    'django-appdata==0.1.6',
    'django-cms==3.4.5',
    'djangocms-text-ckeditor==3.4.0',
    'django-filer==1.2.5',
    'django-parler==1.8',
    'django-reversion==1.10.2',
    'django-sortedm2m==1.5.0',
    'django-taggit==0.22.2',
    'lxml==4.3.4',
    'pytz==2017.2',
    'six==1.11.0',
    'python-dateutil==2.6.1',

    # Transitive dependencies
    'babel==2.5.1',
    'django-classy-tags==0.8.0',
    'django-formtools==1.0',
    'django-mptt==0.8.6',
    'django-phonenumber-field==1.3.0',
    'django-polymorphic==0.8.1',
    'django-sekizai==0.10.0',
    'django-treebeard==4.0.1',
    'djangocms-admin-style==1.2.5',
]

# https://pypi.python.org/pypi?%3Aaction=list_classifiers
CLASSIFIERS = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Django :: 1.6',
    'Framework :: Django :: 1.7',
    'Framework :: Django :: 1.8',
    'Framework :: Django :: 1.9',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 2.6',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3.3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content :: News/Diary',
    'Topic :: Software Development',
    'Topic :: Software Development :: Libraries :: Application Frameworks',
]

setup(
    name='aldryn-newsblog',
    version=__version__,
    description='Adds blogging and newsing capabilities to django CMS',
    author='Divio AG',
    author_email='info@divio.ch',
    url='https://github.com/aldryn/aldryn-newsblog',
    packages=find_packages(),
    license='LICENSE.txt',
    platforms=['OS Independent'],
    install_requires=REQUIREMENTS,
    classifiers=CLASSIFIERS,
    long_description=open('README.rst').read(),
    include_package_data=True,
    zip_safe=False,
    test_suite="test_settings.run",
)
