# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 02:55
from __future__ import unicode_literals

import aldryn_common.admin_fields.sortedm2m
from django.db import migrations

def move_authors(apps, schema_editor):
    Article = apps.get_model('aldryn_newsblog', 'Article')
    print('migrating authors...')
    for article in Article.objects.all():
        print('author is: ', article.author)
        article.authors = [article.author]
        print('saving article: ', article)
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0018_auto_20160802_1852'),
        ('aldryn_newsblog', '0015_auto_20161208_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, default=None, help_text='Choose and order the authors for this article', related_name='articles', to='aldryn_people.Person'),
        ),
        migrations.RunPython(move_authors),
    ]
